# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python学习\临时工具\重命名本地图片\widowui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReNameForm(object):
    def setupUi(self, ReNameForm):
        ReNameForm.setObjectName("ReNameForm")
        ReNameForm.resize(419, 506)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        ReNameForm.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReNameForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb2 = QtWidgets.QLabel(ReNameForm)
        self.lb2.setText("")
        self.lb2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb2.setObjectName("lb2")
        self.verticalLayout.addWidget(self.lb2)
        self.lb1 = QtWidgets.QLabel(ReNameForm)
        self.lb1.setText("")
        self.lb1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1.setObjectName("lb1")
        self.verticalLayout.addWidget(self.lb1)
        self.splitter = QtWidgets.QSplitter(ReNameForm)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.le1 = QtWidgets.QLineEdit(self.splitter)
        self.le1.setObjectName("le1")
        self.cb1 = QtWidgets.QComboBox(self.splitter)
        self.cb1.setMinimumSize(QtCore.QSize(80, 0))
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.bt1 = QtWidgets.QPushButton(self.splitter)
        self.bt1.setObjectName("bt1")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(ReNameForm)
        self.le1.returnPressed.connect(self.bt1.click)
        QtCore.QMetaObject.connectSlotsByName(ReNameForm)

    def retranslateUi(self, ReNameForm):
        _translate = QtCore.QCoreApplication.translate
        ReNameForm.setWindowTitle(_translate("ReNameForm", "重命名本地图片"))
        self.cb1.setItemText(0, _translate("ReNameForm", ".gif"))
        self.cb1.setItemText(1, _translate("ReNameForm", ".jpg"))
        self.cb1.setItemText(2, _translate("ReNameForm", ".png"))
        self.bt1.setText(_translate("ReNameForm", "开始"))
