# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(272, 417)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/心2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 3, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.genBtn = QtWidgets.QPushButton(self.groupBox)
        self.genBtn.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.genBtn.setFont(font)
        self.genBtn.setObjectName("genBtn")
        self.gridLayout.addWidget(self.genBtn, 0, 0, 1, 1)
        self.formulaBtn = QtWidgets.QPushButton(self.groupBox)
        self.formulaBtn.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.formulaBtn.setFont(font)
        self.formulaBtn.setObjectName("formulaBtn")
        self.gridLayout.addWidget(self.formulaBtn, 0, 1, 1, 1)
        self.tableBtn = QtWidgets.QPushButton(self.groupBox)
        self.tableBtn.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.tableBtn.setFont(font)
        self.tableBtn.setObjectName("tableBtn")
        self.gridLayout.addWidget(self.tableBtn, 1, 0, 1, 1)
        self.openTableBtn = QtWidgets.QPushButton(self.groupBox)
        self.openTableBtn.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.openTableBtn.setFont(font)
        self.openTableBtn.setObjectName("openTableBtn")
        self.gridLayout.addWidget(self.openTableBtn, 1, 1, 1, 1)
        self.mathpixBtn = QtWidgets.QPushButton(self.groupBox)
        self.mathpixBtn.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.mathpixBtn.setFont(font)
        self.mathpixBtn.setObjectName("mathpixBtn")
        self.gridLayout.addWidget(self.mathpixBtn, 2, 0, 1, 1)
        self.copyBtn = QtWidgets.QPushButton(self.groupBox)
        self.copyBtn.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.copyBtn.setFont(font)
        self.copyBtn.setObjectName("copyBtn")
        self.gridLayout.addWidget(self.copyBtn, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.textShow = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.textShow.setFont(font)
        self.textShow.setMarkdown("")
        self.textShow.setObjectName("textShow")
        self.verticalLayout.addWidget(self.textShow)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 272, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "青灵OCR V0.2"))
        self.groupBox.setTitle(_translate("MainWindow", "执行："))
        self.genBtn.setText(_translate("MainWindow", "通用识别"))
        self.formulaBtn.setText(_translate("MainWindow", "公式识别"))
        self.tableBtn.setText(_translate("MainWindow", "表格识别"))
        self.openTableBtn.setText(_translate("MainWindow", "表格下载"))
        self.mathpixBtn.setText(_translate("MainWindow", "MathPix"))
        self.copyBtn.setText(_translate("MainWindow", "复制"))
        self.textShow.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑 Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
import qrec_rc
