# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\python 学习\正则计算器\ReHouseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReHouseWindow(object):
    def setupUi(self, ReHouseWindow):
        ReHouseWindow.setObjectName("ReHouseWindow")
        ReHouseWindow.resize(333, 374)
        self.centralwidget = QtWidgets.QWidget(ReHouseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(12, -1, 12, -1)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.l01 = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.l01.setFont(font)
        self.l01.setObjectName("l01")
        item = QtWidgets.QListWidgetItem()
        self.l01.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.l01.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.l01.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.l01.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.l01.addItem(item)
        self.gridLayout.addWidget(self.l01, 0, 0, 1, 2)
        self.readBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.readBtn.setFont(font)
        self.readBtn.setObjectName("readBtn")
        self.gridLayout.addWidget(self.readBtn, 1, 0, 1, 1)
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.delBtn.setFont(font)
        self.delBtn.setObjectName("delBtn")
        self.gridLayout.addWidget(self.delBtn, 1, 1, 1, 1)
        ReHouseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReHouseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 26))
        self.menubar.setObjectName("menubar")
        ReHouseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReHouseWindow)
        self.statusbar.setObjectName("statusbar")
        ReHouseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReHouseWindow)
        QtCore.QMetaObject.connectSlotsByName(ReHouseWindow)

    def retranslateUi(self, ReHouseWindow):
        _translate = QtCore.QCoreApplication.translate
        ReHouseWindow.setWindowTitle(_translate("ReHouseWindow", "正则仓库"))
        __sortingEnabled = self.l01.isSortingEnabled()
        self.l01.setSortingEnabled(False)
        item = self.l01.item(0)
        item.setText(_translate("ReHouseWindow", "New Item"))
        item = self.l01.item(1)
        item.setText(_translate("ReHouseWindow", "New Item"))
        item = self.l01.item(2)
        item.setText(_translate("ReHouseWindow", "New Item"))
        item = self.l01.item(3)
        item.setText(_translate("ReHouseWindow", "New Item"))
        item = self.l01.item(4)
        item.setText(_translate("ReHouseWindow", "New Item"))
        self.l01.setSortingEnabled(__sortingEnabled)
        self.readBtn.setText(_translate("ReHouseWindow", "Read"))
        self.delBtn.setText(_translate("ReHouseWindow", "Delete"))
